import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

function MyApp({ Component, pageProps }: AppProps) {
  return (
  <>
    <Head>
      <title>XYLO-test-FE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      />
    </Head>
    <Component {...pageProps} />
  </>
  );
}

export default MyApp
