import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Nav, NavItem, NavLink} from 'reactstrap'
import { faSearch } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>XYLO FrontEnd Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        />
      </Head>
      <div id="header">
        <Nav justified className={styles.headerTop}>
          <NavItem style={{position: 'relative', textAlign: 'left'}}>
            <NavLink className={styles.navLink}>
              <a href='#' className={styles.search}>
                <FontAwesomeIcon icon={faSearch} />
              </a>
            </NavLink>
          </NavItem>
          <NavItem style={{position: 'relative', textAlign: 'center'}}>
            <NavLink className={styles.navLink} style={{color:'#fff'}}>
              DanielScrivner
            </NavLink>
          </NavItem>
          <NavItem style={{position: 'relative', textAlign: 'right'}}>
            <NavLink className={styles.navLink}>
              <a href='#' className={styles.subscribe} >
                Subscribe
              </a>
            </NavLink>
          </NavItem>
        </Nav>
        <Nav justified className={styles.headerBottom} >
          <NavItem style={{position: 'relative'}}>
            <NavLink className={styles.whiteColor}>
              <a href="#" className={styles.navLink}>
                Podcast
              </a>
            </NavLink>
          </NavItem>
          <NavItem style={{position: 'relative'}}>
            <NavLink className={styles.whiteColor}>
              <a href="#" className={styles.navLink}>
                Podcast
              </a>
            </NavLink>
          </NavItem><NavItem style={{position: 'relative'}}>
            <NavLink className={styles.whiteColor}>
              <a href="#" className={styles.navLink}>
                Podcast
              </a>
            </NavLink>
          </NavItem><NavItem style={{position: 'relative'}}>
            <NavLink className={styles.whiteColor}>
              <a href="#" className={styles.navLink}>
                Podcast
              </a>
            </NavLink>
          </NavItem>
        </Nav>
      </div>

      <div className={styles.container}>
        
        <main className={styles.main}>
        </main>

        <footer className={styles.footer}>
        </footer>
      </div>
    </>
  )
}

export default Home
